param(
    [switch]$Local,
    [string]$Endpoint,
    [string]$Token,
    [switch]$NoStartManager,
    [switch]$StopManager
)

function Test-LxeManagerPortBusy {
    param([int]$Port)
    $tcp = $null
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect("127.0.0.1", $Port)
        return $true
    } catch {
        return $false
    } finally {
        if ($null -ne $tcp) {
            $tcp.Dispose()
        }
    }
}

function Stop-LxeManagerMcpPort {
    param([int]$Port)

    if (-not (Test-LxeManagerPortBusy -Port $Port)) {
        Write-Host "enable_mcp: port $Port is free."
        return
    }

    Write-Host "enable_mcp: stopping listeners on TCP port $Port (SIGTERM)."
    if (Get-Command fuser -ErrorAction SilentlyContinue) {
        & fuser -k "-SIGTERM" "${Port}/tcp" 2>$null
    } elseif (Get-Command lsof -ErrorAction SilentlyContinue) {
        $raw = & lsof -nP -iTCP:$Port -sTCP:LISTEN -t 2>$null
        if (-not [string]::IsNullOrWhiteSpace($raw)) {
            foreach ($p in ($raw -split "\s+")) {
                if ($p -match "^\d+$") {
                    Stop-Process -Id ([int]$p) -ErrorAction SilentlyContinue
                }
            }
        }
    } elseif ($env:OS -match "Windows") {
        Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
            ForEach-Object {
                Stop-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue
            }
    } else {
        throw "enable_mcp: install fuser or lsof to stop the manager on port $Port"
    }

    for ($i = 0; $i -lt 40; $i++) {
        if (-not (Test-LxeManagerPortBusy -Port $Port)) {
            Write-Host "enable_mcp: port $Port is free."
            return
        }
        Start-Sleep -Milliseconds 100
    }

    Write-Warning "enable_mcp: port $Port still busy; SIGKILL."
    if (Get-Command fuser -ErrorAction SilentlyContinue) {
        & fuser -k "-SIGKILL" "${Port}/tcp" 2>$null
    } elseif (Get-Command lsof -ErrorAction SilentlyContinue) {
        $raw = & lsof -nP -iTCP:$Port -sTCP:LISTEN -t 2>$null
        if (-not [string]::IsNullOrWhiteSpace($raw)) {
            foreach ($p in ($raw -split "\s+")) {
                if ($p -match "^\d+$") {
                    Stop-Process -Id ([int]$p) -Force -ErrorAction SilentlyContinue
                }
            }
        }
    }
    Start-Sleep -Milliseconds 200

    if (Test-LxeManagerPortBusy -Port $Port) {
        throw "enable_mcp: could not free port $Port"
    }
    Write-Host "enable_mcp: port $Port is free."
}

if ($Local.IsPresent -and -not [string]::IsNullOrWhiteSpace($Endpoint)) {
    throw "enable_mcp: use only one of -Local or -Endpoint"
}
if ($StopManager.IsPresent -and ($Local.IsPresent -or -not [string]::IsNullOrWhiteSpace($Endpoint))) {
    throw "enable_mcp: -StopManager cannot be combined with -Local or -Endpoint"
}

$ScriptDir = $PSScriptRoot
$RepoRoot = Split-Path -Parent (Split-Path -Parent $ScriptDir)
$ConfigPath = if ($Env:LXE_EDITOR_CODEX_CONFIG_PATH) {
    $Env:LXE_EDITOR_CODEX_CONFIG_PATH
} else {
    Join-Path $RepoRoot ".codex/config.toml"
}

$mcpPort = 3880
if (-not [string]::IsNullOrWhiteSpace($Env:LXE_MANAGER_PORT)) {
    $mcpPort = [int]$Env:LXE_MANAGER_PORT
}

if ($StopManager.IsPresent) {
    Stop-LxeManagerMcpPort -Port $mcpPort
    exit 0
}

$Writer = Join-Path $ScriptDir "enable_mcp_write_config.py"

$mode = "inherit"
$setUrl = $null
if ($Local.IsPresent) {
    $mode = "local"
    $setUrl = "http://127.0.0.1:$mcpPort/mcp"
} elseif (-not [string]::IsNullOrWhiteSpace($Endpoint)) {
    $mode = "endpoint"
    $setUrl = $Endpoint
}

$tokenAutoGenerated = $false
if ([string]::IsNullOrWhiteSpace($Token)) {
    if ($mode -eq "local") {
        $Token = & python3 -c "import secrets; print(secrets.token_urlsafe(32))"
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
        $tokenAutoGenerated = $true
    } else {
        throw "enable_mcp: -Token is required (except with -Local)"
    }
}

if ($mode -eq "inherit") {
    & python3 $Writer --config $ConfigPath --keep-url
} else {
    & python3 $Writer --config $ConfigPath --set-url $setUrl
}
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

if ($mode -eq "local") {
    Write-Host "lxe_manager MCP target: local $setUrl"
} elseif ($mode -eq "endpoint") {
    Write-Host "lxe_manager MCP target: remote $setUrl"
} else {
    Write-Host "lxe_manager MCP target: keep existing url in $ConfigPath"
}

$Env:LXE_MANAGER_MCP_BEARER_TOKEN = $Token

if ($tokenAutoGenerated) {
    Write-Host "enable_mcp: generated local bearer token."
    [Console]::Error.WriteLine("export LXE_MANAGER_MCP_BEARER_TOKEN=$Token")
}

if ($mode -eq "local" -and -not $NoStartManager.IsPresent) {
    if (Test-LxeManagerPortBusy -Port $mcpPort) {
        Write-Host "enable_mcp: 127.0.0.1:$mcpPort busy; stopping existing listener(s) before start_mcp.ps1."
        Stop-LxeManagerMcpPort -Port $mcpPort
    }
    $logDir = Join-Path $RepoRoot "data/lxe_manager"
    New-Item -ItemType Directory -Force -Path $logDir | Out-Null
    $startScript = Join-Path $ScriptDir "start_mcp.ps1"
    $shell = if (Get-Command pwsh -ErrorAction SilentlyContinue) { "pwsh" } else { "powershell" }
    $startArgs = @(
        "-NoProfile"
        "-ExecutionPolicy", "Bypass"
        "-File", $startScript
    )

    if ($PSVersionTable.PSVersion.Major -ge 7) {
        Start-Process -FilePath $shell -ArgumentList $startArgs -WorkingDirectory $RepoRoot -WindowStyle Hidden -Environment @{
            LXE_MANAGER_MCP_BEARER_TOKEN = $Token
            LXE_MANAGER_PORT               = "$mcpPort"
        } | Out-Null
    } else {
        $psi = New-Object System.Diagnostics.ProcessStartInfo -Property @{
            FileName         = $shell
            Arguments        = "-NoProfile -ExecutionPolicy Bypass -File `"$startScript`""
            WorkingDirectory = $RepoRoot
            UseShellExecute  = $false
            CreateNoWindow   = $true
        }
        [void]$psi.EnvironmentVariables.Remove("LXE_MANAGER_MCP_BEARER_TOKEN")
        [void]$psi.EnvironmentVariables.Remove("LXE_MANAGER_PORT")
        $psi.EnvironmentVariables["LXE_MANAGER_MCP_BEARER_TOKEN"] = $Token
        $psi.EnvironmentVariables["LXE_MANAGER_PORT"] = "$mcpPort"
        [System.Diagnostics.Process]::Start($psi) | Out-Null
    }
    $mcpLog = Join-Path $RepoRoot "data/lxe_manager/mcp.log"
    Write-Host "enable_mcp: started start_mcp.ps1 in the background with this LXE_MANAGER_MCP_BEARER_TOKEN (log: $mcpLog)."
}
