#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path


def normalize_name(name: str) -> str:
    return name.upper()


def is_cmake_safe_env_name(name: str) -> bool:
    if not name:
        return False
    for ch in name:
        if ch.isalnum() or ch == "_":
            continue
        return False
    return True


def normalize_path(value: str) -> str:
    return value.replace("\\", "/").rstrip("/")


def merge_value(child: str, original: str) -> str:
    if ";" in child or ";" in original:
        merged: list[str] = []
        seen: set[str] = set()
        for raw in (child.split(";") + original.split(";")):
            item = raw.strip()
            if not item:
                continue
            dedupe_key = item.lower()
            if dedupe_key in seen:
                continue
            seen.add(dedupe_key)
            merged.append(item)
        return ";".join(merged)
    return child


def choose_bracket(value: str) -> tuple[str, str]:
    for count in range(1, 8):
        eq = "=" * count
        close = f"]{eq}]"
        if close not in value:
            return (f"[{eq}[", close)
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return ('"', escaped + '"')


def write_cmake(output_cmake: Path, merged_env: dict[str, str], log_path: Path) -> None:
    lines = [
        "# Generated by cmake/windows_msvc_env_dump.py",
        f"set(LX_WINDOWS_MSVC_ENV_LOG_PATH [=[{log_path.as_posix()}]=])",
    ]
    for name in sorted(merged_env):
        if not is_cmake_safe_env_name(name):
            continue
        value = merged_env[name]
        open_delim, close_delim = choose_bracket(value)
        if open_delim == '"':
            lines.append(f"set(ENV{{{name}}} {close_delim})")
        else:
            lines.append(f"set(ENV{{{name}}} {open_delim}{value}{close_delim})")
    output_cmake.write_text("\n".join(lines) + "\n", encoding="utf-8")


def find_vsdevcmd(explicit_root: str) -> tuple[Path, Path]:
    candidates: list[tuple[Path, Path]] = []

    if explicit_root:
        root = Path(explicit_root)
        direct = root / "Common7" / "Tools" / "VsDevCmd.bat"
        if direct.exists():
            return root, direct
        if root.exists():
            for year_dir in sorted(root.iterdir(), reverse=True):
                if not year_dir.is_dir() or not year_dir.name.isdigit():
                    continue
                if int(year_dir.name) < 2022:
                    continue
                for sku in ("Community", "Professional", "Enterprise", "BuildTools", "Preview"):
                    candidate_root = year_dir / sku
                    candidate_script = candidate_root / "Common7" / "Tools" / "VsDevCmd.bat"
                    if candidate_script.exists():
                        return candidate_root, candidate_script
        raise FileNotFoundError(
            f"Explicit LX_WINDOWS_VS_INSTALLATION_PATH does not contain a usable VsDevCmd.bat: {explicit_root}"
        )

    roots: list[Path] = []
    for env_name in ("ProgramFiles", "ProgramFiles(x86)"):
        env_value = os.environ.get(env_name)
        if env_value:
            roots.append(Path(env_value) / "Microsoft Visual Studio")

    seen_roots: set[str] = set()
    for root in roots:
        root_key = str(root).lower()
        if root_key in seen_roots or not root.exists():
            continue
        seen_roots.add(root_key)
        for year_dir in sorted(root.iterdir(), reverse=True):
            if not year_dir.is_dir() or not year_dir.name.isdigit():
                continue
            if int(year_dir.name) < 2022:
                continue
            for sku in ("Community", "Professional", "Enterprise", "BuildTools", "Preview"):
                candidate_root = year_dir / sku
                candidate_script = candidate_root / "Common7" / "Tools" / "VsDevCmd.bat"
                if candidate_script.exists():
                    candidates.append((candidate_root, candidate_script))

    if not candidates:
        raise FileNotFoundError("Unable to find VsDevCmd.bat under a supported Visual Studio 2022+ installation.")

    return candidates[0]


def build_cmd_script(
    vs_root: Path,
    vsdevcmd: Path,
    python_exe: Path,
    script_path: Path,
    output_cmake: Path,
    output_log: Path,
    debug_enabled: bool,
) -> str:
    lines = [
        "@echo off",
        f'cd /d "{vs_root}"',
        "set VSCMD_SKIP_SENDTELEMETRY=1",
    ]
    if debug_enabled:
        lines.append("set VSCMD_DEBUG=3")
    lines.extend(
        [
            f'call "{vsdevcmd}" -host_arch=x64 -arch=x64',
            "if errorlevel 1 exit /b %errorlevel%",
            f'"{python_exe}" "{script_path}"'
            f' --dump-current-env'
            f' --output-cmake "{output_cmake}"'
            f' --output-log "{output_log}"'
            f' --vs-root "{vs_root}"'
            f' --vsdevcmd "{vsdevcmd}"',
            "exit /b %errorlevel%",
        ]
    )
    return "\r\n".join(lines) + "\r\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dump-current-env", action="store_true")
    parser.add_argument("--output-cmake", required=True)
    parser.add_argument("--output-log", required=True)
    parser.add_argument("--vs-root", default="")
    parser.add_argument("--vsdevcmd", default="")
    parser.add_argument("--explicit-vs-root", default="")
    parser.add_argument("--debug-enabled", choices=("0", "1"), default="0")
    args = parser.parse_args()

    output_cmake = Path(args.output_cmake)
    output_log = Path(args.output_log)
    output_cmake.parent.mkdir(parents=True, exist_ok=True)
    output_log.parent.mkdir(parents=True, exist_ok=True)

    if args.dump_current_env:
        merged_env = {normalize_name(k): v for k, v in os.environ.items()}
        if args.vs_root:
            merged_env["LX_WINDOWS_MSVC_VS_ROOT"] = normalize_path(args.vs_root)
        if args.vsdevcmd:
            merged_env["LX_WINDOWS_MSVC_VSDEVCMD"] = normalize_path(args.vsdevcmd)
        write_cmake(output_cmake, merged_env, output_log)
        return 0

    try:
        vs_root, vsdevcmd = find_vsdevcmd(args.explicit_vs_root)
    except FileNotFoundError as exc:
        sys.stderr.write(str(exc) + "\n")
        return 3

    python_exe = Path(sys.executable)
    script_path = Path(__file__).resolve()
    script_text = build_cmd_script(
        vs_root=vs_root,
        vsdevcmd=vsdevcmd,
        python_exe=python_exe,
        script_path=script_path,
        output_cmake=output_cmake,
        output_log=output_log,
        debug_enabled=args.debug_enabled == "1",
    )

    with tempfile.NamedTemporaryFile("w", suffix=".cmd", delete=False, encoding="utf-8", newline="") as handle:
        handle.write(script_text)
        cmd_script = Path(handle.name)

    try:
        proc = subprocess.run(
            ["cmd", "/d", "/c", str(cmd_script)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
    finally:
        try:
            cmd_script.unlink(missing_ok=True)
        except OSError:
            pass

    full_output = proc.stdout.decode(errors="replace").replace("\r\n", "\n").replace("\r", "\n")
    output_log.write_text(full_output, encoding="utf-8")

    if proc.returncode != 0 or not output_cmake.exists():
        sys.stderr.write(
            f"VsDevCmd bootstrap failed with code {proc.returncode}. "
            f"See {output_log}\n"
        )
        return proc.returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
