#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


def decode_output(data: bytes) -> str:
    for encoding in ("utf-8", "mbcs", sys.getdefaultencoding()):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("utf-8", errors="replace")


def normalize_name(name: str) -> str:
    return name.upper()


def merge_value(child: str, original: str) -> str:
    if ";" in child or ";" in original:
      merged: list[str] = []
      seen: set[str] = set()
      for raw in (child.split(";") + original.split(";")):
          item = raw.strip()
          if not item:
              continue
          dedupe_key = item.lower()
          if dedupe_key in seen:
              continue
          seen.add(dedupe_key)
          merged.append(item)
      return ";".join(merged)
    return child


def choose_bracket(value: str) -> tuple[str, str]:
    for count in range(1, 8):
        eq = "=" * count
        close = f"]{eq}]"
        if close not in value:
            return (f"[{eq}[", close)
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return ('"', escaped + '"')


def write_cmake(output_cmake: Path, merged_env: dict[str, str], log_path: Path) -> None:
    lines = [
        "# Generated by cmake/windows_msvc_env_dump.py",
        f"set(LX_WINDOWS_MSVC_ENV_LOG_PATH [=[{log_path.as_posix()}]=])",
    ]
    for name in sorted(merged_env):
        value = merged_env[name]
        open_delim, close_delim = choose_bracket(value)
        if open_delim == '"':
            lines.append(f"set(ENV{{{name}}} {close_delim})")
        else:
            lines.append(f"set(ENV{{{name}}} {open_delim}{value}{close_delim})")
    output_cmake.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cmd-script", required=True)
    parser.add_argument("--output-cmake", required=True)
    parser.add_argument("--output-log", required=True)
    parser.add_argument("--env-begin-marker", required=True)
    parser.add_argument("--env-end-marker", required=True)
    args = parser.parse_args()

    cmd_script = Path(args.cmd_script)
    output_cmake = Path(args.output_cmake)
    output_log = Path(args.output_log)
    output_cmake.parent.mkdir(parents=True, exist_ok=True)
    output_log.parent.mkdir(parents=True, exist_ok=True)

    proc = subprocess.run(
        ["cmd", "/d", "/c", str(cmd_script)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )

    full_output = decode_output(proc.stdout).replace("\r\n", "\n").replace("\r", "\n")
    output_log.write_text(full_output, encoding="utf-8")

    if proc.returncode != 0:
        sys.stderr.write(
            f"VsDevCmd bootstrap failed with code {proc.returncode}. "
            f"See {output_log}\n"
        )
        return proc.returncode

    begin_token = args.env_begin_marker + "\n"
    end_token = "\n" + args.env_end_marker
    begin = full_output.find(begin_token)
    end = full_output.find(end_token, begin + len(begin_token) if begin != -1 else 0)
    if begin == -1 or end == -1 or end <= begin:
        sys.stderr.write(
            f"Failed to isolate final environment snapshot from bootstrap output. "
            f"See {output_log}\n"
        )
        return 2

    snapshot = full_output[begin + len(begin_token):end]

    original_env = {normalize_name(k): v for k, v in os.environ.items()}
    child_env: dict[str, str] = {}
    for line in snapshot.split("\n"):
        if not line or "=" not in line or line.startswith("="):
            continue
        name, value = line.split("=", 1)
        child_env[normalize_name(name)] = value

    merged_env = dict(original_env)
    for name, child_value in child_env.items():
        original_value = merged_env.get(name, "")
        merged_env[name] = merge_value(child_value, original_value)

    write_cmake(output_cmake, merged_env, output_log)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
